"""Add url column

Revision ID: 2d84bffd0bda
Revises: 0a0e8f39f2ea
Create Date: 2026-08-24 15:15:21.745322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d84bffd0bda'
down_revision: Union[str, Sequence[str], None] = '0a0e8f39f2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_events', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_events', 'url')
    # ### end Alembic commands ###
